name: ChestShop
version: '${project.version}'
main: de.waterdropmc.chestshop.ChestShop
authors: [ Hekates ]
description: ChestShop system for the WaterdropMC network.
website: waterdropmc.de

################################################################
#   ______  __                   __   / _\| |__    ___   _ __  #
#  |      ||  |--..-----..-----.|  |_ \ \ | '_ \  / _ \ | '_ \ #
#  |   ---||     ||  -__||__ --||   _|_\ \| | | || (_) || |_) |#
#  |______||__|__||_____||_____||____|\__/|_| |_| \___/ | .__/ #
########################################################|_|#####
#   .___       .  .    ,      .__         .  . __ #
#   [__. .._.  |  | _.-+-_ ._.|  \._._ ._ |\/|/  `#
#   |  (_|[    |/\|(_] |(/,[  |__/[ (_)[_)|  |\__.#
###################################################
